# These are supported funding model platforms

github: junyuzhan # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://ko-fi.com/yourname', 'https://patreon.com/yourname']
